"""rename address

Revision ID: 5bcadf7fb303
Revises: 34bf85d1bf2e
Create Date: 2024-06-26 13:39:10.388916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcadf7fb303'
down_revision = '34bf85d1bf2e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('location')

# 
# 
# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
#     op.drop_column('departments', 'address')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
#     op.drop_column('departments', 'location')
#     # ### end Alembic commands ###
